### ISSUE TITLE
https xmlrpc support needed for wordpress

### ISSUE THREAD

**Issue by nanonaren** [byorgey/BlogLiterately#16]
It seems that wordpress.com only supports https for the xmlrpc.php url. Trying to post on http gives:
BlogLiterately: user error (301 Moved Permanently )

Of course, trying to post with https gives
BlogLiterately: user error (https not supported)

Help? Meanwhile, is there a way for me to upload new posts? Can I copy the --html-only output to online editor? Will I get same results?

See also:
https://mypersonalblog1984.wordpress.com/2015/01/11/broken-xmlrpc-on-wordpress-com/

**Comment by byorgey** [comment]
Thanks for the report! This will affect me too if I ever get back to
blogging again, so I'll try to take a look at it soon. (Also, patches
welcome.) In the meantime, yes, pasting the output of --html-only into the
editor should work fine as a temporary workaround.

**Comment by nanonaren** [comment]
I think I can fix it by using the `http-client` and `http-client-tls` packages to make the requests instead of the `HTTP` package depedency in `haxr`. It seems I wouldn't have to touch this project. Does that sound like a good way to go?

**Comment by byorgey** [comment]
Yes, I think you are right that it is `haxr` that needs to be fixed and not `BlogLiterately` itself.  I know that the `HTTP` package does not support https, so it needs to be replaced, though I do not know much about potential replacements or how much work it would be.  See also https://github.com/byorgey/haxr/issues/4 .

**Comment by byorgey** [comment]
Very happy to say that I finally figured out how to upgrade `haxr`, and that `BlogLiterately-0.8.1` (just released to Hackage) now works with Wordpress again!  You just have to update your Wordpress XML-RPC URL to start with `https://`.

**Comment by nanonaren** [comment]
Awesome!
