### ISSUE TITLE
lens 4.7 support

### ISSUE THREAD

**Issue by snoyberg** [byorgey/BlogLiterately#17]
I'm opening the issue here since I [closed the relevant Stackage issue](https://github.com/fpco/stackage/commit/e62226e92c9904deb7748469dc414e5653f642d1). When lens 4.7 is supported, please ping me here so that I can add BlogLiterately back to Stackage builds.

**Comment by byorgey** [comment]
@snoyberg , I've just uploaded `BlogLiterately-0.7.1.8`, which should be good to be re-added to Stackage.  Sorry for the long delay, and I'll try to be more responsive in the future!

**Comment by snoyberg** [comment]
Cool, added back. I couldn't add back BlogLiterately-diagrams due to GHC 7.10 support missing (and a few other upper bounds).

**Comment by byorgey** [comment]
Ah, right, I'll update `BlogLiterately-diagrams` as well and let you know.

**Comment by byorgey** [comment]
@snoyberg, I've now finally uploaded `BlogLiterately-diagrams-0.2`, which I as far as I know you should be able to add back.

**Comment by snoyberg** [comment]
Cool, added back.
