### ISSUE TITLE
hscolour has a new version

### ISSUE THREAD

**Issue by nomeata** [byorgey/BlogLiterately#19]
hscolour-1.22 has been released, but BlogLiterately still supports only 1.20.*. Please consider upgrading BlogLiterately.

**Comment by byorgey** [comment]
Uploaded `BlogLiterately-0.7.1.8`.  Sorry for the delay.  As noted elsewhere, this release still does not work with Wordpress---I'm working on that.  But at least it will build and can be used to generate HTML.
