### ISSUE TITLE
Interpreter error: Could not find module 'Diagrams.Prelude' or 'Diagrams.Backend.Rasterific'

### ISSUE THREAD

**Issue by sid-kap** [byorgey/BlogLiterately#24]
Here is the output I get when I run `BlogLiteratelyD test.md` on the example from https://www.stackage.org/lts-3.20/package/BlogLiterately-diagrams-0.2.0.1:
```

Interpreter error:
/tmp/sidharth/Diagram1804289383846930886.hs:4:8:
    Could not find module ‘Diagrams.Prelude’
    Use -v to see a list of the files searched for.
/tmp/sidharth/Diagram1804289383846930886.hs:5:8:
    Could not find module ‘Diagrams.Backend.Rasterific’
    Use -v to see a list of the files searched for.


<p>NOTE: Square brackets below should be replaced by curly braces. Haddock chokes on curly braces.</p>
<p>Here is a green square:</p>
<pre><code>dia = gSq
Interpreter error:
/tmp/sidharth/Diagram1804289383846930886.hs:4:8:
    Could not find module ‘Diagrams.Prelude’
    Use -v to see a list of the files searched for.
/tmp/sidharth/Diagram1804289383846930886.hs:5:8:
    Could not find module ‘Diagrams.Backend.Rasterific’
    Use -v to see a list of the files searched for.
</code></pre>
<p>Green squares like <code>gSq</code>[.dia height=‘16’] and blue circles like <code>circle 1 # fc blue</code>[.dia height=‘16’] are extremely important.</p>
<div id="references" class="references">

</div>
```

Even after running `stack install diagrams-lib diagrams-rasterific`, I still get the same error. How do I make sure that BlogLiteratelyD is loading the correct libraries before running?

**Comment by byorgey** [comment]
How did you install `BlogLiteratelyD`?

**Comment by sid-kap** [comment]
`stack install BlogLiterately-diagrams`

**Comment by byorgey** [comment]
And then how do you run it?  `stack exec BlogLiteratelyD test.md` ?

**Comment by byorgey** [comment]
Running it from a global install is probably not going to work since it needs to have the diagrams packages in the current package DB (so that it can compile diagrams code).

**Comment by sid-kap** [comment]
That solves my problem! `BlogLiteratelyD test.md` did not work, but `stack exec BlogLiteratelyD test.md` works. 
Thanks so much for your help!

**Comment by byorgey** [comment]
Great!
