### ISSUE TITLE
Bindings in literate haskell don't seem to work

### ISSUE THREAD

**Issue by sid-kap** [byorgey/BlogLiterately#25]
According to the documentation, 
>The entire literate Haskell document itself will be loaded into ghci before evaluating the expressions, so expressions may reference anything in scope.

This doesn't seem to work for me. The following markdown
```md

    ```haskell
    x = 5
    ```

    ```ghci
    :show bindings
    ```

```

produces the following output (with the command `BlogLiteratelyD -g test.md`):
```
x = 5
ghci> :show bindings
  it :: () = ()
```

So it seems that the binding for `x` did not work.

**Comment by byorgey** [comment]
Hi @sid-kap ,
```
    ```haskell
    x = 5
    ```
```
is Markdown syntax which typesets some Haskell code, but it is not actual Haskell code in the sense that you can load it into ghci.  Instead, the idea is that in a literate Haskell document you set off Haskell code using "bird tracks", like this:
```
    > x = 5
```
Such bindings should indeed be in scope in `ghci` blocks. (And they will also be typeset just like a `haskell` block would be.)

**Comment by sid-kap** [comment]
Changing the example to 

    > x = 5

    ```ghci
    :show bindings
    ```
does not fix the problem.

**Comment by byorgey** [comment]
Hmm, how about
```
  > x = 5

  ```ghci
  x
  ```
```
Does that work?

**Comment by sid-kap** [comment]
Nope

**Comment by byorgey** [comment]
What does it output?

**Comment by sid-kap** [comment]
Here is the output:

> x = 5
ghci> :show bindings
  it :: () = ()

ghci> x
ghci> print x

**Comment by byorgey** [comment]
That still has `:show bindings` in it.  Can you try removing that and just put `x` by itself in the `ghci` block?  I suspect that a command like `:show bindings` messes up the (very hacky) way that the ghci output gets parsed.

**Comment by sid-kap** [comment]
Hmm. I removed all instances of `:show bindings` and it still doesn't work. There is no output after `x` and `print x`.

**Comment by byorgey** [comment]
Strange.  Can you paste the exact contents of your `.lhs` file and the exact output produced by `BlogLiterately`?

**Comment by sid-kap** [comment]
`test.md`:

    > x = 5

    ```ghci
    x
    print x
    ```

I'm running the command:
```
stack exec BlogLiteratelyD -- -g test.md > test.html
```

and the HTML output is
```html
<pre class="sourceCode haskell"><code class="sourceCode haskell"><span style="">&gt;</span> <span style="">x</span> <span style="color: red;">=</span> <span class="hs-num">5</span>
</code></pre>
<pre><code><span style="color: gray;">ghci&gt; </span>x
<span style="color: gray;">ghci&gt; </span>print x</code></pre>
<div id="references" class="references">

</div>
```

**Comment by byorgey** [comment]
Try naming the file `test.lhs` instead of `test.md`?

**Comment by sid-kap** [comment]
That fixed it. Sorry for the noise!

**Comment by byorgey** [comment]
Ah, good.  No worries!
