### ISSUE TITLE
How to deal with block quotes?

### ISSUE THREAD

**Issue by ivan-m** [byorgey/BlogLiterately#29]
The downside of using bird tracks for literate Haskell is that the same syntax is used for [block quotes](http://pandoc.org/README.html#block-quotations) by Pandoc in Markdown.

If I'm not using bird tracks, is it possible to disable my Markdown being parsed as if it did?

Note that there is a work-around of having a second line of the quote going onto the next line without a `>` as follows:

    > line 1
      line 2

**Comment by byorgey** [comment]
Another workaround is to use actual <blockquote> HTML tags (possibly indented one space).  But in any case it should be possible to add a flag for parsing as normal markdown without literate Haskell, I'll look into it.

**Comment by byorgey** [comment]
I added a flag, `--no-lit-haskell`, which lets you turn off the literate Haskell processing.  Let me know if it works for you.  Unfortunately you must give it as a command-line flag, i.e. you can't put it in a `[BLOpts]` block, since by the time you have read the file it is too late.

**Comment by ivan-m** [comment]
Ta.  I'm happy enough using it from the command-line.
